version: "3"
services:
  redis-rdb:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis_db/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6381:6379"

  redis-aof:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis_aof/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6380:6379"

  beanstalkd:
    image: schickling/beanstalkd
    ports:
      - "11300:11300"
